# Generated by Django 4.1.1 on 2022-09-13 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Фракция')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Фракция',
                'verbose_name_plural': 'Фракции',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Имя персонажа')),
                ('about', models.TextField(blank=True, verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='photos/characters', verbose_name='Фото')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('skil1', models.TextField(blank=True, verbose_name='Основная')),
                ('skil2', models.TextField(blank=True, verbose_name='Особая')),
                ('skil3', models.TextField(blank=True, verbose_name='Особая')),
                ('skil4', models.TextField(blank=True, verbose_name='Особая')),
                ('skil5', models.TextField(blank=True, verbose_name='Лидерская')),
                ('skil6', models.TextField(blank=True, verbose_name='Уник.')),
                ('skil7', models.TextField(blank=True, verbose_name='Уник.')),
                ('skil8', models.TextField(blank=True, verbose_name='Уник.')),
                ('skil9', models.TextField(blank=True, verbose_name='Уник.')),
                ('skil10', models.TextField(blank=True, verbose_name='Уник.')),
                ('skil11', models.TextField(blank=True, verbose_name='Абсолютная')),
                ('abil1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название Основной')),
                ('abil2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название Особая')),
                ('abil3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название Особая')),
                ('abil4', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название Особой')),
                ('abil5', models.CharField(blank=True, max_length=50, null=True, verbose_name='Лдерская')),
                ('abil6', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название Уник.')),
                ('abil7', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название Уник.')),
                ('abil8', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название Уник.')),
                ('abil9', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название Уник.')),
                ('abil10', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название Уник.')),
                ('abil11', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название Абсолютной')),
                ('photo_skill_1', models.ImageField(blank=True, null=True, upload_to='photos/characters/skils', verbose_name='Основная')),
                ('photo_skill_2', models.ImageField(blank=True, null=True, upload_to='photos/characters/skils', verbose_name='Особая')),
                ('photo_skill_3', models.ImageField(blank=True, null=True, upload_to='photos/characters/skils', verbose_name='Особая')),
                ('photo_skill_4', models.ImageField(blank=True, null=True, upload_to='photos/characters/skils', verbose_name='Особая')),
                ('photo_skill_5', models.ImageField(blank=True, null=True, upload_to='photos/characters/skils', verbose_name='Лидерская')),
                ('photo_skill_6', models.ImageField(blank=True, null=True, upload_to='photos/characters/skils', verbose_name='Уник.')),
                ('photo_skill_7', models.ImageField(blank=True, null=True, upload_to='photos/characters/skils', verbose_name='Уник.')),
                ('photo_skill_8', models.ImageField(blank=True, null=True, upload_to='photos/characters/skils', verbose_name='Уник.')),
                ('photo_skill_9', models.ImageField(blank=True, null=True, upload_to='photos/characters/skils', verbose_name='Уник.')),
                ('photo_skill_10', models.ImageField(blank=True, null=True, upload_to='photos/characters/skils', verbose_name='Уник.')),
                ('photo_skill_11', models.ImageField(blank=True, null=True, upload_to='photos/characters/skils', verbose_name='Абсолютная')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.category', verbose_name='Фракция')),
            ],
            options={
                'verbose_name': 'Персонажи ЗВ',
                'verbose_name_plural': 'Персонажи ЗВ',
                'ordering': ['time_create', 'title'],
            },
        ),
    ]
