# Generated by Django 4.1.1 on 2022-09-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['title', 'time_create'], 'verbose_name': 'Персонажи ЗВ', 'verbose_name_plural': 'Персонажи ЗВ'},
        ),
        migrations.AlterField(
            model_name='character',
            name='abil1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Основная'),
        ),
        migrations.AlterField(
            model_name='character',
            name='abil10',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Уник.'),
        ),
        migrations.AlterField(
            model_name='character',
            name='abil11',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Абсолютная'),
        ),
        migrations.AlterField(
            model_name='character',
            name='abil2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Особая'),
        ),
        migrations.AlterField(
            model_name='character',
            name='abil3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Особая'),
        ),
        migrations.AlterField(
            model_name='character',
            name='abil4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Особая'),
        ),
        migrations.AlterField(
            model_name='character',
            name='abil5',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Лидерская'),
        ),
        migrations.AlterField(
            model_name='character',
            name='abil6',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Уник.'),
        ),
        migrations.AlterField(
            model_name='character',
            name='abil7',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Уник.'),
        ),
        migrations.AlterField(
            model_name='character',
            name='abil8',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Уник.'),
        ),
        migrations.AlterField(
            model_name='character',
            name='abil9',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Уник.'),
        ),
        migrations.AlterField(
            model_name='character',
            name='skil1',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='character',
            name='skil10',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='character',
            name='skil11',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='character',
            name='skil2',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='character',
            name='skil3',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='character',
            name='skil4',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='character',
            name='skil5',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='character',
            name='skil6',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='character',
            name='skil7',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='character',
            name='skil8',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='character',
            name='skil9',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
    ]
